In [8]:
import h5py
import numpy as np 
import matplotlib.pyplot as plt
import tools
from scipy.optimize import curve_fit



In [9]:
def read_wilson_loops(filename, B, path = "Configuration", data_name = "loops"):

    all_data = []

    with h5py.File(filename, "r") as f:

        config_keys = list(f[path].keys())

        for cfg in config_keys: 

            T_keys = list(f[f"{path}/{cfg}"].keys())
            cfg_data = []

            for T in T_keys:

                data = f[f"{path}/{cfg}/{T}/{data_name}"][:]
                cfg_data.append(data)

            all_data.append(cfg_data)

    all_data = np.array(all_data)
    means = []
    stds = []

    for r in range(all_data.shape[2]):

        means_r = []
        stds_r = []

        for nt in range(all_data.shape[1]):

            data = all_data[:, nt, r,0]
            #print("Shape of data:", data.shape)
            #print(all_data.shape)
            #print(all_data[0][0].shape)
            #print(data)
            mean, std = tools.bootstrap(B, data)

            means_r.append(mean)
            stds_r.append(std)
        
        means.append(means_r)
        stds.append(stds_r)
    return np.array(means), np.array(stds)

In [10]:
means, stds  = read_wilson_loops("../h5/Wilson867.h5",200)

print(means)
print(stds)

[[0.73762051 0.56886578 0.46357005 0.36598021 0.29003945 0.22450444]
 [0.57269228 0.37320276 0.26856004 0.19119312 0.13946987 0.09136501]
 [0.45254018 0.26470347 0.15883153 0.124798   0.06680111 0.03490156]
 [0.35552635 0.1863754  0.10368362 0.05711745 0.04520372 0.03286191]
 [0.289017   0.12197502 0.07146231 0.03864643 0.03515592 0.00848602]
 [0.22841578 0.10471581 0.06525781 0.04649157 0.00984272 0.01896319]]
[[0.00382102 0.00525026 0.00648955 0.0080893  0.00778436 0.00767421]
 [0.00599954 0.00705815 0.0076017  0.00858062 0.00779004 0.00726421]
 [0.00671191 0.00884308 0.00780243 0.00851671 0.00766542 0.00769479]
 [0.0078998  0.007831   0.00874413 0.00831892 0.00758531 0.00712573]
 [0.00842128 0.00808277 0.0084627  0.00678064 0.00777875 0.00756295]
 [0.00732483 0.00830847 0.00812017 0.00789607 0.00733565 0.00795827]]
